/* SPDX-License-Identifier: MIT */
/* @generated by size-class-gen — DO NOT EDIT. Source of truth: tools/size-class-gen/size-classes.json. Regenerate: cargo xtask gen. */
#ifndef TOPOMALLOC_TABLES_H
#define TOPOMALLOC_TABLES_H

#include <stdint.h>

#define TOPOMALLOC_PAGE_SIZE 16384u
#define TOPOMALLOC_QUANTUM 16u
#define TOPOMALLOC_TINY_MIN 16u
#define TOPOMALLOC_SMALL_MAX 128u
#define TOPOMALLOC_NUM_SIZE_CLASSES 8u

typedef struct topomalloc_size_class {
    uint32_t size;
    uint32_t align;
    uint32_t slab_pages;
    uint32_t objects_per_slab;
    uint32_t batch;
    uint32_t max_local_capacity;
} topomalloc_size_class_t;

static const topomalloc_size_class_t
    topomalloc_size_classes[TOPOMALLOC_NUM_SIZE_CLASSES] = {
        { 16u, 16u, 1u, 1024u, 32u, 256u },
        { 32u, 16u, 1u, 512u, 32u, 256u },
        { 48u, 16u, 1u, 341u, 32u, 256u },
        { 64u, 16u, 1u, 256u, 32u, 256u },
        { 80u, 16u, 1u, 204u, 32u, 256u },
        { 96u, 16u, 1u, 170u, 32u, 256u },
        { 112u, 16u, 1u, 146u, 32u, 256u },
        { 128u, 16u, 1u, 128u, 32u, 256u },
};

static const uint8_t topomalloc_size_to_class[8] = { 0, 1, 2, 3, 4, 5, 6, 7 };

#endif /* TOPOMALLOC_TABLES_H */
